# Generated by Django 6.0.1 on 2026-01-30 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_category_listing_is_active_and_more'),
        ('providers', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('travel_date', models.DateField()),
                ('total_seats', models.IntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_listings', to='providers.provider')),
            ],
        ),
    ]
